# HTTP Server
server:
  port: 8888

spring:
  # Spring Cloud Config Server Repository
  application:
     name: cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Sergiolsz/CloudConfig
          clone-on-start: true
          
  # Spring properties in case you use different profiles
  profiles:
    active: dev
